namespace TKernel
{
    //! Class Message_Algorithm is intended to be the base class for
    //! classes implementing algorithms or any operations that need
    //! to provide extended information on its execution to the
    //! caller / user.
    //!
    //! It provides generic mechanism for management of the execution
    //! status, collection and output of messages.
    //!
    //! The algorithm uses methods SetStatus() to set an execution status.
    //! It is possible to associate a status with a number or a string
    //! (second argument of SetStatus() methods) to indicate precisely
    //! the item (object, element etc.) in the input data which caused
    //! the problem.
    //!
    //! Each execution status generated by the algorithm has associated
    //! text message that should be defined in the resource file loaded
    //! with call to Message_MsgFile::LoadFile().
    //!
    //! The messages corresponding to the statuses generated during the
    //! algorithm execution are output to Message_Messenger using
    //! methods SendMessages(). If status have associated numbers
    //! or strings, they are included in the message body in place of
    //! "%s" placeholder which should be present in the message text.
    //!
    //! The name of the message text in the resource file is constructed
    //! from name of the class and name of the status, separated by dot,
    //! for instance:
    //!
    //! .TObj_CheckModel.Alarm2
    //! Error: Some objects (%s) have references to dead object(s)
    //!
    //! If message for the status is not found with prefix of
    //! the current class type, the same message is searched for the base
    //! class(es) recursively.
    //!
    //! Message can be set explicitly for the status; in this case the
    //! above procedure is not used and supplied message is used as is.
    //!
    //! The messages are output to the messenger, stored in the field;
    //! though messenger can be changed, it is guaranteed to be non-null.
    //! By default, Message::DefaultMessenger() is used.
    public class Message_Algorithm
    {
        public void SetStatus(Message_Status theStat)
        {
            myStatus.Set(theStat);

        }  //! Returns copy of exec status of algorithm
        public Message_ExecStatus GetStatus()
        {
            return myStatus;


        }
        public void ClearStatus()
        {
            myStatus.Clear();
            /*myReportIntegers.Nullify();
            myReportStrings.Nullify();
            myReportMessages.Nullify();*/
        }
        Message_ExecStatus myStatus = new Message_ExecStatus();
        //Message_Messenger myMessenger;

    }
}